[target.aarch64-linux-android]
linker = "aarch64-linux-android35-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[env]
CC_aarch64_linux_android = "aarch64-linux-android35-clang"
CXX_aarch64_linux_android = "aarch64-linux-android35-clang++"
AR_aarch64_linux_android = "llvm-ar"
